// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAd2eIR4xbDoIUT1SjkKZqCmvuL-WXDmng",
    authDomain: "otostopcunungalaksirehbe-7758e.firebaseapp.com",
    projectId: "otostopcunungalaksirehbe-7758e",
    storageBucket: "otostopcunungalaksirehbe-7758e.appspot.com",
    messagingSenderId: "832557440851",
    appId: "1:832557440851:web:56eebdf48dae9c387e8ba6",
    measurementId: "G-251C5D6RHL",
    databaseURL: 'https://otostopcunungalaksirehbe-7758e-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAd2eIR4xbDoIUT1SjkKZqCmvuL-WXDmng',
      appId: '1:832557440851:android:56eebdf48dae9c387e8ba6',
      messagingSenderId: '832557440851',
      projectId: 'otostopcunungalaksirehbe-7758e',
      storageBucket: 'otostopcunungalaksirehbe-7758e.appspot.com',
      databaseURL: 'https://otostopcunungalaksirehbe-7758e-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBrVR9v_Tm8zY7bmbjSf5zGm1ijpBeHEI8',
      appId: '1:832557440851:android:56eebdf48dae9c387e8ba6',
      messagingSenderId: '832557440851',
      projectId: 'otostopcunungalaksirehbe-7758e',
      storageBucket: 'otostopcunungalaksirehbe-7758e.appspot.com',
      iosClientId: '726989396106-t2jrf5dfas8b3ii5nm707dl9332pui5l.apps.googleusercontent.com',
      iosBundleId: 'com.example.flutterAuthUi',
      databaseURL: 'https://otostopcunungalaksirehbe-7758e-default-rtdb.firebaseio.com/'

  );
}
